config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :timelines, only: :index do
    collection do
      get "activities"
    end
  end

  resources :users, only: [:edit, :update]
  post 'posts/create', to: 'posts#create', as: :posts

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  apipie
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      post 'add_friend' => 'dev_cities#add_friend', as: :add_friend
      get 'friend_list' => 'dev_cities#friend_list', as: :friend_list
      post 'common_friend' => 'dev_cities#common_friend', as: :common_friend
      post 'subscribe' => 'dev_cities#subscribe', as: :subscribe
      post 'block' => 'dev_cities#block', as: :block
      post 'receive_updates' => 'dev_cities#receive_updates', as: :receive_updates
      match '*a' => 'errors#routing', via: :all
    end
  end
end

app/views/shared/_banner_devise.html.erb
<%= image_tag "Banner Devise.png", :alt => "Banner Devise", :style => "max-width: 570px; float: right;", :id => "bannerDevise" %>

<script type="text/javascript">
  $(document).ready(function() {
    var contentHeight = $("#modalContent").height();
    $("#bannerDevise").css("height", contentHeight)
  });
</script>

app/views/shared/_footer.html.erb
<hr>
<footer>
  <p>&copy; 2018 DevCity, Inc.</p>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg fixed-top">
  <div class="container">
    <a class="navbar-brand" href="<%= root_path %>"><%= image_tag "Logo.png", :alt => "Logo" %></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <ul class="navbar-nav ml-auto">
      <% if current_user.present? %>
        <li class="nav-item" style="float: left; margin: 20px;">
          <%= link_to "Timelines", timelines_path %>
        </li>
        <%= form_for(timelines_path, :url => {:controller => "/timelines", :action => "index"}, html: { method: :get, class: "form-inline", style: "margin-right: 20px;" }) do %>
          <div class="form-group">
            <%= text_field_tag :search, @search, placeholder: "Search users or posts", class: "form-control", :required => true %>
          </div>
        <% end %>
        <div class="dropdown">
          <a href="#" class="btn btn-info dropdown-toggle" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag current_user.profile_picture.thumb.url, :alt => "User Image", :class => "img-thumbnail rounded", :style => "max-width: 50px;" %>
            <span><%= current_user.email %></span>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
            <%= link_to "Log out", destroy_user_session_path, :method => :DELETE, :class => "dropdown-item" %>
            <%= link_to "Edit Profile", edit_user_registration_path, :class => "dropdown-item" %>
          </div>
        </div>
      <% else %>
        <li class="nav-item">
          <%= link_to "Log in", new_user_session_path, :class => "btn btn-success" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, :class => "btn btn-primary" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

<% if params[:controller].eql?("home") %>
  <div class="jumbotron">
    <div class="container jumbo-container">
      <h1>Devcity Friends!</h1>
      <h3>Chat with new people around the world.</h3>
      <p>Meet millions of new people from all over the world, wherever you are. Have a good chat, make new friends or even find the love of your life. Because life is all about the people you meet.</p>
    </div>
  </div>
<% end %>

app/views/shared/_info.html.erb
<div class="card">
  <% if user.profile_picture.blank? %>
    <img class="card-img-top img-fluid" src="http://placehold.it/900x400">
  <% else %>
    <%= image_tag user.profile_picture.medium.url, :alt => "User Image", :style => "max-width: 150px; margin: 10px auto;" %>
  <% end %>
  <div class="card-body">
    <h6 class="card-title" style="text-align: center;"><%= user.email %> | <%= user.username %></h6>
    <h6 style="text-align: center;">
      <a class="badge badge-primary" role="button" data-toggle="modal" data-target="#friendList" href="javascript:void(0)" style="color: #fff;"><%= user.friends.count %> Friends</a> |
      <a class="badge badge-success" role="button" href="javascript:void(0)" onclick="$('#navMyPost').click();" style="color: #fff;"><%= user.posts.count %> Posts</a>
    </h6>
    <% if user.id != current_user.id %>
      <div class="row btn-action">
        <div class="col-md-12">
          <% if current_user.is_act?(user, "is_friend") %>
            <%= link_to "Unfriend", activities_timelines_path(:act => "unfriend", :target => user.id), :class => "btn btn-danger" %>
          <% else %>
            <%= link_to "Add Friend", activities_timelines_path(:act => "add_friend", :target => user.email), :class => "btn btn-primary" %>
          <% end %>
        </div>
      </div>
      <div class="row btn-action">
        <div class="col-md-12">
          <% if current_user.is_act?(user, "is_subscribe") %>
            <%= link_to "Unsubscribe", activities_timelines_path(:act => "unsubscribe", :target => user.id), :class => "btn btn-danger" %>
          <% else %>
            <%= link_to "Subscribe", activities_timelines_path(:act => "subscribe", :target => user.email), :class => "btn btn-info" %>
          <% end %>
        </div>
      </div>
      <div class="row btn-action">
        <div class="col-md-12">
          <% if current_user.is_act?(user, "is_block") %>
            <%= link_to "Unblock", activities_timelines_path(:act => "unblock", :target => user.id), :class => "btn btn-success" %>
          <% else %>
            <%= link_to "Block", activities_timelines_path(:act => "block", :target => user.email), :class => "btn btn-danger" %>
          <% end %>
        </div>
      </div>
    <% end %>
    <p class="card-text"><%= user.bio %></p>
  </div>
</div>